# Generated by Django 6.0.3 on 2026-06-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('transaction_completed', 'Transaction Completed'), ('transaction_failed', 'Transaction Failed'), ('transaction_rejected', 'Transaction Rejected'), ('deposit_received', 'Deposit Received'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('referral_reward', 'Referral Reward'), ('crypto_sent', 'Crypto Sent'), ('crypto_received', 'Crypto Received'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
