# Generated by Django 6.0.3 on 2026-06-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='reference_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
