# Generated by Django 6.0.3 on 2026-05-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiarybankaccount',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
