# Generated by Django 6.0.3 on 2026-07-15 17:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hd_wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TatumWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tatum_event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, db_index=True, max_length=255)),
                ('chain', models.CharField(blank=True, max_length=50)),
                ('signature', models.CharField(blank=True, max_length=512)),
                ('payload', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TatumAddressSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tatum_subscription_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('address', models.CharField(db_index=True, max_length=255)),
                ('chain', models.CharField(max_length=50)),
                ('subscription_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='active', max_length=20)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hd_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tatum_subscription', to='hd_wallets.hdwalletaddress')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
