# Generated by Django 6.0.3 on 2026-05-25 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0011_transaction_crypto_usd_price'),
    ]

    operations = [
    ]
