# Generated by Django 6.0.3 on 2026-06-11 00:08

import broker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0012_transaction_custody_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(default=broker.models.generate_transaction_id, editable=False, max_length=14, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payout_method',
            field=models.CharField(blank=True, choices=[('ngn_wallet', 'NGN wallet')], max_length=30),
        ),
    ]
