# Generated by Django 6.0.3 on 2026-06-11 00:41

import broker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0013_alter_transaction_id_alter_transaction_payout_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(default=broker.models.generate_transaction_id, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
