# Generated by Django 6.0.3 on 2026-07-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0015_transaction_expires_at_fail_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Auto-set to 24h after creation for pending_payment transactions. Null for pre-migration records.', null=True),
        ),
    ]
