# Generated by Django 6.0.3 on 2026-07-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0016_alter_transaction_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Draft transactions are hidden from user history until action is taken.'),
        ),
    ]
