# Generated by Django 6.0.3 on 2026-07-15 17:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broker', '0016_alter_transaction_expires_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HdWalletDerivationIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chain', models.CharField(help_text='e.g. ethereum, bsc, polygon, celo, tron, solana', max_length=30)),
                ('network', models.CharField(blank=True, help_text='e.g. erc20, bep20, trc20, sol — the wallet-level label', max_length=50)),
                ('derivation_index', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hd_derivation_indexes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'chain', 'network')},
            },
        ),
        migrations.CreateModel(
            name='HdWalletAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(help_text='e.g. USDT, ETH, BNB', max_length=20)),
                ('network', models.CharField(help_text='e.g. erc20, bep20, trc20, sol', max_length=50)),
                ('chain', models.CharField(help_text='e.g. ethereum, bsc, tron, solana', max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('derivation_path', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hd_wallet_addresses', to=settings.AUTH_USER_MODEL)),
                ('derivation_index', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hd_addresses', to='hd_wallets.hdwalletderivationindex')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'currency', 'network')},
            },
        ),
        migrations.CreateModel(
            name='OnChainWithdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=20)),
                ('network', models.CharField(blank=True, max_length=50)),
                ('chain', models.CharField(blank=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('to_address', models.CharField(max_length=255)),
                ('txid', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('broadcast', 'Broadcast'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('signer_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_chain_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnChainDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=20)),
                ('network', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('txid', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('credited', 'Credited'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('tatum_subscription_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='on_chain_deposit', to='broker.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_chain_deposits', to=settings.AUTH_USER_MODEL)),
                ('wallet_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='on_chain_deposits', to='hd_wallets.hdwalletaddress')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'currency', 'status'], name='hd_wallets__user_id_f47727_idx'), models.Index(fields=['txid', 'currency'], name='hd_wallets__txid_1caf4e_idx')],
            },
        ),
    ]
