# Generated by Django 6.0.3 on 2026-06-11 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cryptotransfer',
            new_name='transfers_c_sender__75554b_idx',
            old_name='transfers_sender_idx',
        ),
        migrations.RenameIndex(
            model_name='cryptotransfer',
            new_name='transfers_c_recipie_65af17_idx',
            old_name='transfers_recipient_idx',
        ),
        migrations.RenameIndex(
            model_name='cryptotransfer',
            new_name='transfers_c_status_a9e37f_idx',
            old_name='transfers_status_idx',
        ),
    ]
