# Generated by Django 6.0.3 on 2026-04-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_alter_rateconfiguration_asset_alter_ratequote_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateconfiguration',
            name='asset',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether'), ('BNB', 'BNB'), ('SOL', 'Solana'), ('XRP', 'XRP'), ('TRX', 'TRON'), ('LTC', 'Litecoin'), ('DOGE', 'Dogecoin'), ('BCH', 'Bitcoin Cash'), ('ADA', 'Cardano'), ('MATIC', 'Polygon'), ('DOT', 'Polkadot'), ('LINK', 'Chainlink'), ('AVAX', 'Avalanche'), ('UNI', 'Uniswap'), ('XLM', 'Stellar'), ('ATOM', 'Cosmos'), ('ETC', 'Ethereum Classic'), ('TON', 'Toncoin')], default='BTC', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='ratequote',
            name='asset',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether'), ('BNB', 'BNB'), ('SOL', 'Solana'), ('XRP', 'XRP'), ('TRX', 'TRON'), ('LTC', 'Litecoin'), ('DOGE', 'Dogecoin'), ('BCH', 'Bitcoin Cash'), ('ADA', 'Cardano'), ('MATIC', 'Polygon'), ('DOT', 'Polkadot'), ('LINK', 'Chainlink'), ('AVAX', 'Avalanche'), ('UNI', 'Uniswap'), ('XLM', 'Stellar'), ('ATOM', 'Cosmos'), ('ETC', 'Ethereum Classic'), ('TON', 'Toncoin')], default='BTC', max_length=10),
        ),
    ]
