# Generated by Django 6.0.3 on 2026-06-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0008_customuser_kyc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
