# Generated by Django 6.0.3 on 2026-06-11 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_add_treasury_snapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='treasurysnapshot',
            new_name='broker_trea_asset_fcfde6_idx',
            old_name='broker_tres_asset_synced_idx',
        ),
    ]
