# Generated by Django 6.0.3 on 2026-06-12 15:07

import wallets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0008_rename_broker_tres_asset_synced_idx_broker_trea_asset_fcfde6_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposittransaction',
            name='id',
            field=models.CharField(default=wallets.models.generate_deposit_id, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
