# Generated by Django 6.0.3 on 2026-05-23 22:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustodyAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sub_partner_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nowpayments_custody_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustodyDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('pay_address', models.CharField(blank=True, max_length=255)),
                ('pay_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('payment_status', models.CharField(default='pending', max_length=30)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custody_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='nowpayments.custodyaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nowpayments_custody_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
